export const DEFAULT_DATA = {
  Status: 200,
  Message: "OK",
  Data: [
    { Time: "00:00", Capacity: 2, OriginalCapacity: 2, Eco: false },
    { Time: "01:00", Capacity: 2, OriginalCapacity: 2, Eco: true },
    { Time: "02:00", Capacity: 0, OriginalCapacity: 2, Eco: true },
    { Time: "03:00", Capacity: 2, OriginalCapacity: 2, Eco: true },
    { Time: "04:00", Capacity: 1, OriginalCapacity: 2, Eco: true },
    { Time: "05:00", Capacity: 0, OriginalCapacity: 2, Eco: true },
    { Time: "06:00", Capacity: 0, OriginalCapacity: 2, Eco: true },
    { Time: "07:00", Capacity: 2, OriginalCapacity: 2, Eco: true },
    { Time: "08:00", Capacity: 1, OriginalCapacity: 2, Eco: true },
    { Time: "09:00", Capacity: 1, OriginalCapacity: 2, Eco: true },
    { Time: "10:00", Capacity: 0, OriginalCapacity: 2, Eco: false },
    { Time: "11:00", Capacity: 2, OriginalCapacity: 2, Eco: false },
    { Time: "12:00", Capacity: 2, OriginalCapacity: 2, Eco: false },
    { Time: "13:00", Capacity: 1, OriginalCapacity: 2, Eco: true },
    { Time: "14:00", Capacity: 0, OriginalCapacity: 2, Eco: true },
    { Time: "15:00", Capacity: 1, OriginalCapacity: 2, Eco: true },
    { Time: "16:00", Capacity: 1, OriginalCapacity: 2, Eco: true },
    { Time: "17:00", Capacity: 0, OriginalCapacity: 2, Eco: true },
    { Time: "18:00", Capacity: 0, OriginalCapacity: 2, Eco: false },
    { Time: "19:00", Capacity: 1, OriginalCapacity: 2, Eco: false },
    { Time: "20:00", Capacity: 0, OriginalCapacity: 2, Eco: false },
    { Time: "21:00", Capacity: 0, OriginalCapacity: 2, Eco: true },
    { Time: "22:00", Capacity: 1, OriginalCapacity: 2, Eco: true },
    { Time: "23:00", Capacity: 0, OriginalCapacity: 2, Eco: false },
  ],
};
